### ISSUE TITLE
 Basic Cornell Box

### ISSUE THREAD

**Issue by kugimasa** [kugimasa/WebGPUTracer#3]
Adjusting stuff to RayTracingTheRestOfYourLife
https://raytracing.github.io/books/RayTracingTheRestOfYourLife.html

### TODO
- [x] Fix code to a more general style.
- [x] Adjust Window size.
- [x] Scene setting.
   - [x] Cornell Box 
   - [x] Sphere
   - [x] Box
       - [x] Add Box Class
       - [x] Translation, Rotaion
- [x] The scene is darker than the sample image. (Noise is biased? Second bounce is wrong?)
   => Directly sampling the light was correct.
- [x] The scene is brighter than the sample image when using MIS.
   => The light setting was stronger 👼

**Comment by kugimasa** [comment]
Rendered with: 0f48b67807066a017ab6e824573ff7d7e57fbd2c
![000](https://github.com/kugimasa/WebGPUTracer/assets/40158101/bec501b2-5cfb-453a-8069-a035d0915ab2)

A bit dark ... ?
I'll have to make a box to compare with the reference image.

**Comment by kugimasa** [comment]
Rendered with: 4a18df5
![000](https://github.com/kugimasa/WebGPUTracer/assets/40158101/2197ba35-9839-40ac-a120-a745eb3613ce)

Adjusted window size to 512 x 512.
The size had to be a multiple of 256.
(May be related to the device setting...??)
```

Uncaptured device error: type 1 (bytesPerRow (3200) is not a multiple of 256.
 - While encoding [CommandEncoder].CopyTextureToBuffer([Texture], [Buffer "PixelBuffer"], [Extent3D width:800, height:800, depthOrArrayLayers:1]).
)
Uncaptured device error: type 1 ([Invalid CommandBuffer] is invalid.
 - While calling [Queue "Default Queue"].Submit([[Invalid CommandBuffer]])
)
```

**Comment by kugimasa** [comment]
Rendered with: d328333
![000](https://github.com/kugimasa/WebGPUTracer/assets/40158101/23853b73-44ed-495a-807d-5347ad3a5f5d)

It seems like the light is only bouncing once.

**Comment by kugimasa** [comment]
Rendered with: 0f9a9f3
Calculate light pdf directly from light rect area.
![calcuate_direclty_light_pdf](https://github.com/kugimasa/WebGPUTracer/assets/40158101/05e3fa94-d778-446b-b124-6fd097f30974)

Calculate light pdf from hit.
![calcuate_from_hit](https://github.com/kugimasa/WebGPUTracer/assets/40158101/d5246892-acba-4c83-8073-09c1691e8f18)

**Comment by kugimasa** [comment]
# Final Image
Rendered with: 004c8d7
![Image](https://github.com/kugimasa/WebGPUTracer/assets/40158101/30bd9da8-8c8f-46ae-a6c6-57a1ccfb3dd2)
Still a little bit noisy but the lighting seems to be the same.
